// custom icons
import {
  TingoDashboard as Dashboard,
  TingoMedia as Media,
  TingoProjects as Projects,
  TingoComment as Comment,
  TingoManagement as Management,
  TingoAuditLog as AuditLog,
  TingoSetting as Setting,
  TingoSearchIcon as Search,
  TingoBellIcon as BellIcon,
  MediaPost as MediaPostIcon,
  PastProject as PastProjectIcon,
  CurrentProject as CurrentProjectIcon,
  FutureProject as FutureProjectIcon,
  LoginImg as LoginIcon,
  VerifyBackIcon,
  PortfolioBalance,
  WalletBalance,
  ArtSecLogo,
  ArtSecBell,
  ArtSecFavourite,
  ArtSecCurrencyIcon,
  ArtSecCurrencyLineIcon,
  ArtSecWithdrawalSuccessIcon,
  ArtSecWhatsApp,
  ArtSecFacebook2,
  ArtSecInstagram,
  ArtSecTwitter2,
  ArtSecEye,
  ArtSecCertified,
  ArtSecHoldBid,
  ArtSecPlaceBid,
  ArtSecReport,
  ArtSecMenuIcon,
  ArtSecCongratulation,
  ArtSecArtistDomain,
  ArtSecShare,
  ArtSecMenuDot,
  ArtSecHistoryLine,
  ArtSecEyeClose,
  ArtSecEyeOpen,
  ArtSecEmailVerifyIcon,
  ArtSecChatBot,
  ArtSecInputSuccess,
  VisaCard,
  MasterCard,
  Generic,
  PaymentFailed,
  AccountActivationCompleted,
} from "../components/common/dmf-icon";

// REACT ICON LIBRARY
import {
  BsSearch as SearchIcon,
  BsArrowRightShort as ArtSecArrowRight,
  BsArrowUpShort as ArtSecArrowUp,
} from "react-icons/bs";

import {
  AiOutlineCloseCircle as CloseIcon,
  AiOutlineUpload as UploadIcon,
  AiOutlineDownload as ArtSecDownload,
} from "react-icons/ai";

import {
  FaMapMarkerAlt as ArtSecMap,
  FaFacebookSquare as ArtSecFacebook,
  FaTwitter as ArtSecTwitter,
  FaPinterest as ArtSecPinterest,
  FaUserAlt as ProfileIcon,
  FaHistory as HistoryIcon,
  FaCreditCard as PaymentMethod,
  FaUpload as ArtSecFileUpload,
} from "react-icons/fa";

import { CgFileDocument as DocumentIcon } from "react-icons/cg"

import { 
  FcGoogle as ArtSecGoogle 
} from "react-icons/fc";



import { MdDeleteForever as ArtSecDelete, MdNotifications as NotifyIcon, MdLogout as LogoutIcon } from "react-icons/md";
import { BiTransfer as ArtSecComparison } from "react-icons/bi";
import { HiOutlineDocumentText as ArtSecCertificate } from "react-icons/hi";

export const icons = {
  ArtSecCertificate,
  ArtSecGoogle,
  ArtSecFacebook,
  ArtSecTwitter,
  ArtSecPinterest,
  Projects,
  Dashboard,
  Media,
  Comment,
  Management,
  AuditLog,
  Setting,
  Search,
  BellIcon,
  MediaPostIcon,
  PastProjectIcon,
  CurrentProjectIcon,
  FutureProjectIcon,
  SearchIcon,
  CloseIcon,
  UploadIcon,
  LoginIcon,
  VerifyBackIcon,
  PortfolioBalance,
  WalletBalance,
  ArtSecLogo,
  ArtSecBell,
  ArtSecArrowRight,
  ArtSecArrowUp,
  ArtSecFavourite,
  ArtSecMap,
  ArtSecDelete,
  ArtSecComparison,
  ArtSecCurrencyIcon,
  ArtSecCurrencyLineIcon,
  ArtSecWithdrawalSuccessIcon,
  ArtSecWhatsApp,
  ArtSecFacebook2,
  ArtSecInstagram,
  ArtSecTwitter2,
  ArtSecEye,
  ArtSecCertified,
  ArtSecDownload,
  ArtSecHoldBid,
  ArtSecPlaceBid,
  ArtSecReport,
  ArtSecMenuIcon,
  ArtSecCongratulation,
  ArtSecArtistDomain,
  ArtSecShare,
  ArtSecMenuDot,
  ArtSecHistoryLine,
  ArtSecEyeClose,
  ArtSecEyeOpen,
  ArtSecEmailVerifyIcon,
  ArtSecChatBot,
  ArtSecInputSuccess,
  VisaCard,
  MasterCard,
  Generic,
  PaymentFailed,
  AccountActivationCompleted,
  ProfileIcon,
  HistoryIcon,
  PaymentMethod,
  DocumentIcon,
  NotifyIcon,
  LogoutIcon,
  ArtSecFileUpload
};
